title: "سایت من"
baseurl: ""   # <-- set to "/REPO-NAME" if this is a project site
url: ""
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      lang: "fa"
      layout: "default"
