title: "سایت من"
description: "مجموعه‌ای از خلاصه‌ها و مطالب فارسی"
baseurl: ""
url: ""
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      lang: "fa"
      layout: "default"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle

plugins: []
