title: "سایت من"
baseurl: ""   # if this is a project page (username.github.io/REPO), set this to "/REPO"
url: ""
permalink: pretty

markdown: kramdown
kramdown:
  input: GFM
  parse_block_html: true

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      lang: "fa"
      layout: "default"
